### ISSUE TITLE
Allow UpdateSketch#update to take a byte array slice

### ISSUE THREAD

**Issue by romseygeek** [apache/datasketches-java#510]
UpdateSketch#update(byte[]) passes its byte array argument to MurmurHash3#hash(byte[],int,int,long) but always uses an offset of 0 and a length of data.length.  Adding a new update method that also takes an offset and a length would allow users to update sketches without having to copy data if their inputs are already references into large byte arrays.

For context, I'm coming from Apache Lucene where term data is almost always passed around as references into these types of large byte arrays, and being able to update sketches like this would be very helpful in cutting down memory copies.  If the maintainers think this would be useful to others I'm happy to open a pull request.

**Comment by leerho** [comment]
@romseygeek 
Any comments on my reply of 2 weeks ago?

**Comment by romseygeek** [comment]
An `update(ByteByffer)` method on all the counting sketches sounds good to me.  Happy to open PRs for these - would you prefer separate ones for each sketch type or a single one for all three?

**Comment by leerho** [comment]
I will get back to you shortly.  It turns out there are 6 places in the library where this would be relevant, and I hate to have you do all that work, so maybe I should do it.  Here are the approximate relative locations:

- .../filters/bloomfilter/BloomFilter.java:212:  public void update(final byte[] data)...
- .../hll/BaseHllSketch.java:363:  public void update(final byte[] data)...
- .../tuple/arrayofdoubles/ArrayOfDoublesUpdatableSketch.java:119:  public void update(final byte[] key, final double[] values)...
- .../tuple/UpdatableSketch.java:135:  public void update(final byte[] key, final U value)...
- .../theta/UnionImpl.java:479:  public void update(final byte[] data)...
- .../theta/UpdateSketch.java:271:  public UpdateReturnState update(final byte[] data)...

Are you still up for it?

**Comment by romseygeek** [comment]
I'll make a start and see how long it takes me to do a couple of them :)

**Comment by leerho** [comment]
That would be great!  Thank you!

**Comment by romseygeek** [comment]
I started out adding an `update(Memory)` method here, but that runs into trouble with `Union` which already has an `update(Memory)` method that does something quite different.  So I think adding an `update(ByteBuffer)` method is probably the way to go (which HLL already has so that's one less place to update).

**Comment by leerho** [comment]
I have been decoding your statement.  I wasn't sure where "here" was, but it must have been in /bloomfilter/ or /sampling/ ?

- The update(Memory) in /filters/ bloomfilter already does what you want.   Unless you also want update(ByteBuffer) as an option.
- I would ignore /sampling/ directory
- As you said, /hll/ already has update(BB), so ignore

That leaves:
- .../tuple/arrayofdoubles/ArrayOfDoublesUpdatableSketch.java
- .../tuple/UpdatableSketch.java
- .../cpc/CpcSketch.java  (somehow this was omitted in the first list !)
- .../theta/UnionImpl.java
- .../theta/UpdateSketch.java

Feel free to do what you can!  I really appreciate the help!

**Comment by leerho** [comment]
Thank you for contributing this.  I haven't had a chance to review it, but will get to it soon.
